version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: simple-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'simple_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  simple-service:
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    command: java -jar simple-service/target/simple-service-0.0.1-SNAPSHOT.jar
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/simple_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  parking-service:
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    command: java -jar parking-service/target/parking-service-0.0.1-SNAPSHOT.jar
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/parking_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

volumes:
  db_data:
