version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: simple-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'simple_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: maven:3.9.6-eclipse-temurin-17
    container_name: simple-app
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/simple_db?useSSL=false&allowPublicKeyRetrieval=true
    command: mvn spring-boot:run

volumes:
  db_data:
